[section#func.wrap.badcall
    [:en] Class [`bad_function_call]
]
[%@library bad_function_call]
[%@library exception[!bad_function_call]]

[para]
[:en]
An exception of type [`bad_function_call] is thrown by [`function::operator()]
([#func.wrap.func.inv]) when the function wrapper object has no target.

[codeblock:synopsis]
namespace std {
  class bad_function_call : public std::exception {
  public:
    // [:en] [#func.wrap.badcall.const], constructor:
    bad_function_call() noexcept;
  };
} // namespace std
[codeblock:end]

[include func.wrap.badcall.const]
